"""add item table

Revision ID: 335fa178f7bd
Revises: e4fd7640f500
Create Date: 2021-08-05 21:09:55.924626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335fa178f7bd'
down_revision = 'e4fd7640f500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=25), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('aisleLocation', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('countryOrigin', sa.String(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('upc', sa.String(), nullable=False),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('productId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
