"""empty message

Revision ID: e438276aa21f
Revises: 335fa178f7bd
Create Date: 2021-08-18 22:04:47.832560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e438276aa21f'
down_revision = '335fa178f7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('seller', sa.String(length=50), nullable=True),
    sa.Column('productName', sa.String(length=25), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('countryOrigin', sa.String(), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('productId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
